<a href="https://colab.research.google.com/github/staffanw/githubTest/blob/main/filtered_thyroid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import sys
assert sys.version_info >= (3, 7)
from packaging import version
import sklearn
assert version.parse(sklearn.__version__) >= version.parse("1.0.1")
import os
import pandas as pd
from zipfile import ZipFile
thyroidDf = pd.DataFrame()

In [6]:
# Step 1: Authenticate
# Place kaggle.json in ~/.kaggle/ or set these environment variables
os.environ['KAGGLE_USERNAME'] = 'staffanwinter'
os.environ['KAGGLE_KEY'] = '636629f94693fac27f01438b51f0fe0b'

# Step 2: Download the dataset
!kaggle datasets download -d aneevinay/thyroid-cancer-recurrence-dataset -p data --unzip

# Step 3: Check the file name
print(os.listdir("data"))

# Step 4: Load into pandas
thyroidDf = pd.read_csv("data/filtered_thyroid_data.csv")  # Update this filename if it's different
print(thyroidDf.head())

Dataset URL: https://www.kaggle.com/datasets/aneevinay/thyroid-cancer-recurrence-dataset
License(s): CC-BY-NC-SA-4.0
['filtered_thyroid_data.csv']
   Age Gender Hx Radiothreapy Adenopathy       Pathology     Focality Risk  \
0   27      F              No         No  Micropapillary    Uni-Focal  Low
1   34      F              No         No  Micropapillary    Uni-Focal  Low
2   30      F              No         No  Micropapillary    Uni-Focal  Low
3   62      F              No         No  Micropapillary    Uni-Focal  Low
4   62      F              No         No  Micropapillary  Multi-Focal  Low

     T   N   M Stage       Response Recurred
0  T1a  N0  M0     I  Indeterminate       No
1  T1a  N0  M0     I      Excellent       No
2  T1a  N0  M0     I      Excellent       No
3  T1a  N0  M0     I      Excellent       No
4  T1a  N0  M0     I      Excellent       No

In [7]:
thyroidDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              383 non-null    int64
 1   Gender           383 non-null    object
 2   Hx Radiothreapy  383 non-null    object
 3   Adenopathy       383 non-null    object
 4   Pathology        383 non-null    object
 5   Focality         383 non-null    object
 6   Risk             383 non-null    object
 7   T                383 non-null    object
 8   N                383 non-null    object
 9   M                383 non-null    object
 10  Stage            383 non-null    object
 11  Response         383 non-null    object
 12  Recurred         383 non-null    object
dtypes: int64(1), object(12)
memory usage: 39.0+ KB

In [11]:
thyroidDf.value_counts()

Age  Gender  Hx Radiothreapy  Adenopathy  Pathology  Focality     Risk          T    N    M   Stage  Response                Recurred
28   F       No               No          Papillary  Uni-Focal    Low           T2   N0   M0  I      Excellent               No          5
26   F       No               No          Papillary  Uni-Focal    Low           T2   N0   M0  I      Excellent               No          5
31   F       No               No          Papillary  Uni-Focal    Low           T2   N0   M0  I      Excellent               No          4
27   F       No               No          Papillary  Uni-Focal    Low           T1b  N0   M0  I      Excellent               No          3
35   F       No               No          Papillary  Uni-Focal    Low           T1b  N0   M0  I      Excellent               No          3
                                                                                                                                        ..
32   M       No               Bilateral   Papillary  Multi-Focal  Intermediate  T3b  N1b  M0  I      Structural Incomplete   Yes         1
     F       No               No          Papillary  Uni-Focal    Low           T3a  N0   M0  I      Excellent               No          1
                                                     Multi-Focal  Intermediate  T4a  N0   M0  I      Excellent               No          1
                                                                                T3a  N0   M0  I      Biochemical Incomplete  No          1
33   M       No               No          Papillary  Uni-Focal    Low           T2   N0   M0  I      Structural Incomplete   Yes         1
Name: count, Length: 330, dtype: int64